name: esque
services:
  devenv:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: esque-devenv
    volumes:
      - jbdevcontainer:/.jbdevcontainer
      - ${HOME}/.ssh:/home/ubuntu/.ssh
      - ${HOME}/.claude:/home/ubuntu/.claude
    command: sleep infinity

volumes:
  jbdevcontainer:
